# ✅ Disable DataSource auto-configuration
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
spring.mvc.hiddenmethod.filter.enabled=true



spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=
spring.datasource.username=
spring.datasource.password=

# ✅ Prevent Hibernate from auto-configuring DB
spring.jpa.database-platform=
spring.jpa.hibernate.ddl-auto=none

# ✅ Set logging level to DEBUG to track issues
logging.level.org.springframework=DEBUG
logging.level.com.example=DEBUG
logging.level.root=INFO

server.port=${PORT:8080}
